version: "3.2"
services:
  db-mssql16.pjwstk.edu.pl:
    container_name: db-mssql16.pjwstk.edu.pl
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"