FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["TemplateAPI/TemplateAPI.csproj", "TemplateAPI/"]
RUN dotnet restore "TemplateAPI/TemplateAPI.csproj"
COPY . .
WORKDIR "/src/TemplateAPI"
RUN dotnet build "TemplateAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TemplateAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TemplateAPI.dll"]
